# Generated by Django 5.2 on 2025-04-11 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email обязателен для заполнения.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "max_length": "Имя пользователя не может превышать 20 символов.",
                    "min_length": "Имя пользователя должно содержать минимум 4 символа.",
                    "unique": "Пользователь с таким именем пользователя уже существует.",
                },
                help_text="Имя пользователя обязательно для заполнения.",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Имя пользователя может содержать только латинские буквы, цифры и _.",
                        regex="^[a-zA-Z0-9_]+$",
                    ),
                    django.core.validators.MinLengthValidator(
                        4, "Имя пользователя должно содержать минимум 4 символа."
                    ),
                ],
                verbose_name="имя пользователя",
            ),
        ),
    ]
